# Generated by Django 3.2.7 on 2022-05-17 12:18

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('activation_code', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether this user should be treated as active.Unselect this instead of deleting account', verbose_name='active')),
            ],
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
    ]
